#!/usr/bin/python

def raise_exception():
    a = 10
    b = "alaa"
    print("{} + {}".format(a + b))
